- name: Placing Uncrustify CFG
  copy:
    src: files/dotfiles/uncrustify/uncrustify.cfg
    dest: "/home/{{ myusername }}/.config/uncrustify.cfg"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing Ncspot CFG
  copy:
    src: files/dotfiles/ncspot/config.toml
    dest: "/home/{{ myusername }}/.config/ncspot/config.toml"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing Kitty CFG
  copy:
    src: files/dotfiles/kitty/kitty.conf
    dest: "/home/{{ myusername }}/.config/kitty/kitty.conf"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing Kitty Theme
  copy:
    src: files/dotfiles/kitty/snazzy.conf
    dest: "/home/{{ myusername }}/.config/kitty/snazzy.conf"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing .sbuildrc
  copy:
    src: files/dotfiles/sbuild/.sbuildrc
    dest: "/home/{{ myusername }}/.sbuildrc"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700