- name: Remove Desktop APT Packages
  apt:
    name: "{{ rempackages }}"
    state: absent
  vars:
    rempackages:
      - libreoffice-*
      - docker
      - docker-engine
      - docker.io
      - ibus
      - plank
      - geary
      - code

- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
- name: Install Desktop APT Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - inxi
      - neovim
      - xclip
      - ncdu
      - tmux
      - openssh-server
      - ubuntu-restricted-extras
      - debconf-utils
      - lftp
      - htop
      - deluge-gtk
      - gnome-mpv
      - calibre
      - whois
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python-pip
      - nomacs
      - snapd-xdg-open
      - asciinema
      - flameshot
      - python-psutil
      - psutils
      - libimage-exiftool-perl
      - python3-pip
      - libcurl4
      - curl
      - gnupg-agent
      - font-manager
      - gnome-calculator
      - valac
      - uncrustify
      - devscripts
      - software-properties-gtk
      - meson
      - gnome-disk-utility
      - dlocate
      - ttf-mscorefonts-installer
      - fonts-emojione
      - ppa-purge
      - pylint
      - gtk-3-examples
      - libgtk-3-0
      - pop-icon-theme-extra
      - pop-gtk-theme
      - hidpi-daemon
      - dialog

- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
