- name: Add Docker's public PGP key to the APT keyring
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: Configure Docker's upstream APT STABLE Repository for 19.10
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    update_cache: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'eoan'

- name: Configure Docker's upstream APT STABLE Repository when NOT 19.10
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release != 'eoan'

- name: Install Docker
  apt:
    name: "docker-ce"
    state: "present"

- name: Install Docker-Compose
  apt:
    name: "docker-compose"
    state: "present"
