- name: Install Snap Packages
  command: 'snap install "{{ item }}"'
  with_items:
    - spotify
    - lxd
    - simplescreenrecorder
    - bitwarden
    - bw
    - icdiff
    - mumble
    - shfmt
    - bluemail
    - review-tools
    - croc
    - standard-notes
    - scrcpy
    - htmldoc
    - polar-bookshelf
    - mailspring
- name: Install Classic Snap Packages
  command: 'snap install "{{ item }}" --classic'
  with_items:
    - go
    - restic
    - snapcraft
    - snapdiff
    - slack

- name: Install Node Snap Package
  command: "snap install node --channel=11/stable --classic"

- name: Install Multipass Snap Package
  command: "snap install multipass --beta --classic"

- name: Install IRCCLOUD Desktop Snap Package
  command: "snap install irccloud --edge"
- name: Install Hugo Extended
  command: "snap install hugo --channel=extended/edge"
