- name: Copy Default Wallpaper
  copy:
    src: files/ubuntu_budgie_01.jpg
    dest: "/home/{{ myusername }}/Pictures/wallpaper.jpg"

- name: Set Wallpaper File Permissions
  file:
    path: "/home/{{ myusername }}/Pictures/wallpaper.jpg"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0775

- name: Set Default Wallpaper
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///home/{{ myusername }}/Pictures/wallpaper.jpg'"
    state: present
    
- name: Set Default Lockscreen Wallpaper
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file:///home/{{ myusername }}/Pictures/wallpaper.jpg'"
    state: present